site_name: Rāpoi Cluster Documentation
nav: 
  - Overview: 'index.md'
  - Documentation:
    - 'Accessing the Cluster': 'accessing_the_cluster.md'
    - 'Basic Commands': 'basic_commands.md'
    - 'Storage and Quotas': 'storage.md'
    - 'Using Partitions': 'partitions.md'
    - 'Preparing your Environment (modules)': 'environment.md'
    - 'New module system' : 'new_mod.md'
    - 'Running Jobs': 'running_jobs.md'
    - 'Parallel Processing': 'parallel_processing.md'
    - 'Managing Jobs': 'managing_jobs.md'
    - 'Connecting to Cloud Providers': 'cloud_providers.md'
    - 'Using Containers': 'containers.md'
    - 'Using Jupyter Notebooks': 'notebooks.md'
    - 'Examples': 'examples.md' 
    - 'Training': 'training.md'
    - 'User Submitted Docs': 'usersub.md'
    - 'FAQ': 'faq.md'
    - Support: support.md


theme: readthedocs
markdown_extensions:
  - toc:
      permalink: True
      baselevel: 1
      toc_depth: 3
  - codehilite
  - footnotes

plugins:
  - search
  - include-markdown
  - mermaid2


extra_css: [extra.css]

site_url: https://vuw-research-computing.github.io/raapoi-docs/